name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  
  # Allow manual runs:
  workflow_dispatch:

  # Reusable workflows!
  # See: https://docs.github.com/en/actions/using-workflows/reusing-workflows
  workflow_call:

  schedule:
    # Run once a month to alert me of bit-rot.
    # See: https://docs.github.com/en/actions/reference/events-that-trigger-workflows#schedule
    # Runs on the default ("main") branch.
    # min h d mon DoW
    - cron: "7 5 3 * *"

env:
  CARGO_TERM_COLOR: always


jobs:
  build:
    strategy:
      matrix:
        os:
        # ubuntu-latest often uses libc much newer than Debian.
        # Use an older version, which should be forward compatible w/ newer ones too.
        - ubuntu-20.04
        - macos-latest
        - windows-latest
      # Don't fail fast, if we have a failure on a specific matrix type
      # we want to know which ones:
      fail-fast: false

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2

    # v2, as of today (June 18, 2023)
    - uses: arduino/setup-protoc@9b1ee5b22b0a3f1feb8c2ff99b32c89b3c3191e9
      with: 
        version: '23.x'
        repo-token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Run Rust Tests
      run: cargo test

    - name: Build Rust
      run: cargo build --release

    - name: Save result
      uses: actions/upload-artifact@v4
      with:
        name: "Diskuto-${{ matrix.os }}"
        path: |
          ./target/release/diskuto
          ./target/release/diskuto.exe
          