name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    uses: ./.github/workflows/build.yml

  release:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Download build artifacts
        id: download
        uses: actions/download-artifact@v4
        with:
          path: ./artifacts

      - name: Create Artifacts
        working-directory: ${{ steps.download.outputs.download-path}}
        run: |
          set -eux

          TAG="${{ github.ref_name }}"
          
          cd Diskuto-macos-latest
          zip -9 "../diskuto-api-macos-${TAG}.zip" diskuto
          cd ..

          cd Diskuto-ubuntu-20.04
          zip -9 "../diskuto-api-linux-${TAG}.zip" diskuto
          cd ..

          cd Diskuto-windows-latest
          zip -9 "../diskuto-api-windows-${TAG}.zip" diskuto.exe
          cd ..

          ls *.zip


      - name: Create the release
        id: release
        # I don't know softprops, but they were recommended by GitHub here:
        # https://github.com/actions/upload-release-asset?tab=readme-ov-file
        uses: softprops/action-gh-release@v2
        with:
          prerelease: contains(github.ref_name, '-rc')
          body: |
            See [CHANGELOG.md] for release notes.
            
            [CHANGELOG.md]: https://github.com/diskuto/diskuto-api/blob/${{ github.ref_name }}/CHANGELOG.md
          files: |
            ${{ steps.download.outputs.download-path}}/*.zip
          
      
